#
# Awesome App Landing Page Config
#

# Be sure all REQUIRED fields are filled out!

#
# General App Info
#
app:
  name: Park Pursuit # REQUIRED - Enter your app name
  ios_id: 1335800270 # REQUIRED - 10 Digit Numeric App ID (lookup in iTunes Connect)
  android_id: com.walkingriver.parkpursuit # Optional - Enter Android app id like: com.example.app

  icon: images/icon-1024.png # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-icon-512.png
  # 512px or greater, square

  #favicon: # uncomment if uploading own favicon
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-favicon.png - can be .ico or .png
  # 16px or greater, square

  # Leave blank to auto-magically populate
  screenshot: images/app-screen-640x1136.png
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-screen-640x1136.png
  # 640x1136px

  #video: # uncomment if prefer to show a video preview in the screen instead of image
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-preview.mp4
  # 640x1136px

  #app_twitter: # uncomment if the app has a twitter account "@my-awesome-app"
  creator_twitter: walkingriver # uncomment if creator has a twitter account "@awesome-dev"
  social_image: /images/icon-1024.png # uncomment and add an image - defaults to icon
  # This will show up when your url is shared on sites like facebook and twitter
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-social_image.png
  # 512px or greater, square or width = 2X height
#
# Marketing
#
marketing_header: A mobile visual scavenger hunt # Optional
marketing_desc: Park Pursuit is a visual scavenger hunt. The game is designed to allow scavenger hunts to be created anywhere in the world. However, living in Central Florida, the Disney Theme Parks seemed to be the natural place to start. As a bonus, we recently added 20 clues to seek from the Brigham Young University Campus in Provo, Utah. <p>To start a hunt, select an available park, and then you will be presented with a series of images. Each image is a clue to a landmark somewhere within that park.</p><p>If you need a hint, tap the "Hint" link (or the ? icon), and the app will tell you the rough compass direction you should seek, along with a snarky comment about your distance from it.</p><p>When you think you have found the landmark, tap the "Found It" link (or the eye icon). The app will compare your current location to the location embedded in the clue itself. You must be within 25 meters of the clue's location to consider it "found." Once found, that image will be marked as found and updated in the list of clues.</p><p>There is no limit to the number of clues or parks you can seek simultaneously. Your progress is saved automatically.</p><p>We intend to add more parks (and not just Disney Parks) to the mix, along with the ability for players to submit their own parks and clues. Watch for application updates.

#
# Social Links
#
# Includes an icon for each username you enter
#
social-links:
  github:
  facebook: ParkPursuit
  twitter: walkingriver
  pinterest:
  instagram: walkingriver
  email: michael@walkingriver.com
  youtube: # channel/<your_long_string> or <user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

#
# Enable/Disable Features & Page Elements
#
enable:
  app_icon: true
  smart_app_banner: true

#
# Device
#
# Available devices:
# * iphone-se-silver-vertical
# * iphone-se-space-gray-vertical
# * ipod-touch-blue-vertical
#
device: iphone-se-silver-vertical # REQUIRED

#
# Theme Settings
#
background_color: "#989898" # Optional
# background_image: /images/backgrounds/58-usersthink-stock-image-web.jpg # Optional - Use Relative path e.g. images/backgrounds/image.jpg
background_image: /images/backgrounds/pp-collage.jpg
text_color: white # Optional
link_color: # Optional
social_link_color: white # Optional
download_button_background_color: "#0191FF" # Optional
download_button_text_color: white; # Optional

#
# Site Info
#
# If you want specific meta info for your <head></head> tags
#
title: Park Pursuit # Optional - Enter your site title
description: A theme-park based mobile visual scavenger hunt -- now with Universal Studios Florida! # Optional - Enter your site description

#
# Google Analytics
#
google_analytics: # Enter your tracking code (e.g. UA-2110908-2) to activate tracking

#
# iTunes Affiliate Program
#
# Sign up here: http://www.apple.com/itunes/affiliates/
#
# Disclaimer:
# This will default to using the author's affiliate token if left blank
#
itunes_affiliate_token: # Optional

#
# !! You don't need to change any of the configuration flags below !!
#

# The release of Awesome App Landing Page that you're using
version: v1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - REAMDE-old.md
